### ISSUE TITLE
Basic Instructions

### ISSUE THREAD

**Issue by mtangoo** [tuyakhov/yii2-json-api#1]
Hi
Could you put basic instructions and usage like installation, usage, what is covered and what is missing?
Thanks

**Comment by tuyakhov** [comment]
Hi @mtangoo
Development is still in progress. I have provided some instructions in [README](https://github.com/tuyakhov/yii2-json-api/blob/master/README.md) Please let me know if you will have any problems during installation or usage.

**Comment by mtangoo** [comment]
Yes I understand, but I wanted to contribute since I have project that requires JSONApi. I will setup this night and see if I find any problem. Thanks for your time.

**Comment by zakdma** [comment]
There is mistake in README
php composer.phar require --prefer-dist tuyakhov/yii2-youtube "dev-master"

I think it must be 
php composer.phar require --prefer-dist tuyakhov/yii2-json-api "dev-master"

**Comment by tuyakhov** [comment]
Thank you @zakdma !
