### ISSUE TITLE
Correct Content-Type

### ISSUE THREAD

**Issue by githubjeka** [tuyakhov/yii2-json-api#10]
If use
```php
class Controller extends \yii\rest\Controller
{
    public $serializer = 'tuyakhov\jsonapi\Serializer';

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/vnd.api+json' => Response::FORMAT_JSON,
                ],
            ]
        ]);
    }
}
```

then you get
![image](https://cloud.githubusercontent.com/assets/874234/21348831/f5c97ca0-c6bf-11e6-8d74-6cd6e7e7e40c.png)

> Servers MUST send all JSON API data in response documents with the header Content-Type: application/vnd.api+json without any media type parameters.
http://jsonapi.org/format/#content-negotiation-servers

**Comment by tuyakhov** [comment]
@githubjeka You need to configure response formatter. Here is an instruction: https://github.com/tuyakhov/yii2-json-api#controlling-json-api-output
