### ISSUE TITLE
Sparse filedsets: query naming problem.

### ISSUE THREAD

**Issue by soap** [tuyakhov/yii2-json-api#20]
First of all, thanks for your great extension.

This is a first Yii2 REST JSONAPI for me. And I think I found a bug in sparse fieldsets standard. When I want to specify fields I will do like this:-
``
?fields[customers]=firstName,lastName,status
``
But it doesn't work. When I look at code in Serializer.php.
``` 
protected function serializeModel(ResourceInterface $model)
    {
        $fields = $this->getRequestedFields();

        $attributes = isset($fields[$model->getType()]) ? $fields[$model->getType()] : [];
```
$model->getType() return singular resource name. But my resource is plural.

If I change to 

``
?fields[customer]=firstName,lastName,status
``
It works. Do this require modification? 

Sorry for my English.
Thanks.

**Comment by tuyakhov** [comment]
Thank you. That is definitely a bug. It has been fixed in https://github.com/tuyakhov/yii2-json-api/pull/14 and will be included in next release.
Please notice, starting from `v0.1.0`, by default camelcase member names like `firstName` or `lastName` will be converted to `first-name`, `last-name`. http://jsonapi.org/recommendations/#naming

**Comment by soap** [comment]
Thanks for your response. I use your extension in my current project. It work for retrieving resources. But for creating I have no luck. 

Do I have to override CreateAction.php of Yii2?  I use ActiveController as API Based controller class. For something like fetching relationship resource (articele/1/author), I point to your ViewRelatedAction. It works.

Sorry for asking here.

**Comment by soap** [comment]
Ok, I found a solution to bring back all attribute as before conversion. Thanks.

**Comment by tuyakhov** [comment]
@soap The CreateAction of Yii2 use `$model->load(Yii::$app->getRequest()->getBodyParams(), '');` to populate model with data, which ignores formName, so it can't be used with JsonApiParser of this extension. Also CreateAction of Yii is not compatible with Json API specification. I am planning to provide a compatible create/update/delete actions in near future. Also check this https://github.com/tuyakhov/yii2-json-api#enabling-json-api-input I think it might help you.
Please let me know if you have any other questions.
PS. It would be if you will share your solution about attribute names. Thanks

**Comment by soap** [comment]
I set one base class as API controller and modify CreateAction and Update Action there. I have also hidden some fields like tenant_id as companyId so I have to check and convert them back.

```
<?php
namespace api\modules\v1\controllers;

use yii\rest\ActiveController;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use yii\filters\ContentNegotiator;

/**
 * Based JSON API version 1.0 Controller
 *
 * @author Prasit Gebsaap
 */
class ApiController extends ActiveController
{
    public $serializer = [
        'class' => 'tuyakhov\jsonapi\Serializer',
        'prepareMemberName' => ['api\common\jsonapi\Inflector', 'var2member'],
        'formatMemberName' => ['api\common\jsonapi\Inflector', 'member2var']
    ];

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/vnd.api+json' => Response::FORMAT_JSON,
                ],
            ]
        ]);
    }

    public function actions()
    {
        $actions = parent::actions();

        $actions['create'] = [
            'class' => 'api\modules\v1\controllers\actions\CreateAction',
            'modelClass' => $this->modelClass,
            'checkAccess' => [$this, 'checkAccess']
        ];

        $actions['update'] = [
            'class' => 'api\modules\v1\controllers\actions\UpdateAction',
            'modelClass' => $this->modelClass,
            'checkAccess' => [$this, 'checkAccess']
        ];
        // See additional configuration in api/config/main.php
        // Url manager URL rule {resources}/{id}/{name}
        // Fetch resource specified by {name} associated to {resources}
        $actions['fetch'] = [
            'class' => 'tuyakhov\jsonapi\actions\ViewRelatedAction',
            'modelClass' => $this->modelClass,
            'checkAccess' => [$this, 'checkAccess'],
        ];

        $actions['uprel'] = [
            'class' => 'tuyakhov\jsonapi\actions\UpdateRelationshipAction',
            'modelClass' => $this->modelClass,
            'checkAccess' => [$this, 'checkAccess'],
        ];

        return $actions;
    }

    protected function verbs()
    {
        $verbs = parent::verbs();

        return $verbs;
    }

    public function prepareDataProvider()
    {
        $model = new $this->modelClass;
        $filters = \Yii::$app->request->get('filter');

        if (empty($filters)) {
            return $model->search([]);
        }

        $fields = $model->fields();
        $safeFilters = [];
        // name => json attribute (integer means no change), attribute => database column
        foreach ($fields as $name => $attribute) {
            if (is_int($name)) {
                $name = $attribute;
            }
            if (array_key_exists($name, $filters)) {
                $safeFilters[$attribute] = $filters[$name];
            }
        }

        return $model->search($safeFilters);
    }

}
```

This is a controller class.
```
<?php
namespace api\modules\v1\controllers;

/**
 * Customer Controller API
 *
 * @author Prasit Gebsaap
 */
class CustomerController extends ApiController
{
    public $modelClass = 'api\modules\v1\models\Customer';

    public function actions()
    {
        $actions = parent::actions();

        // disable the "delete" and "create" actions
        //unset($actions['delete'], $actions['create']);

        // customize the data provider preparation with the "prepareDataProvider()" method
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];

        return $actions;
    }

    /*
    public function prepareDataProvider()
    {
        $model = new $this->modelClass;
        return $model->search(\Yii::$app->request->get());
    }*/

}
```

**Comment by mtangoo** [comment]
Hi @tuyakhov ,
is there any progress on creating JSONAPI actions to replace Yii's? I have tried your create action and works fine in creating the data but then returns `{}` which is not valid JSONAPI.

Any pointer?

**Comment by mtangoo** [comment]
Ignore my question, I forgot to add to my model `implements ResourceInterface` and when added it worked fine!
