### ISSUE TITLE
Field name should be convert according to recommendations for JSON API implementations

### ISSUE THREAD

**Issue by vadimtrunov** [tuyakhov/yii2-json-api#32]
I was found a small mistake when a model with errors serialized. Model attributes not convert according to JSON API standard.

https://github.com/tuyakhov/yii2-json-api/blob/641a17e0611f8d858edd4596a3080facc5d29208/src/Serializer.php#L299

Better not to simply use attribute name, but conver attribute name to a member name:

`           
$memberName = \tuyakhov\jsonapi\Inflector::var2member($name);
`

and then use it:

`'source' => ['pointer' => "/data/attributes/{$memberName}"],`

**Comment by tuyakhov** [comment]
Thank you for reporting this.
Fixed in https://github.com/tuyakhov/yii2-json-api/pull/33
