### ISSUE TITLE
Improve to ResourceTrait:fields

### ISSUE THREAD

**Issue by githubjeka** [tuyakhov/yii2-json-api#4]
Active Record uses fields() by default and it expected when work by API.
Your implement return always [] attributes.

But removal of this method would create another issue. Because ResourceTrait may be used in others non ActiveRecord classes. Probably it requires more efficient approach.

https://github.com/tuyakhov/yii2-json-api/pull/3

**Comment by tuyakhov** [comment]
Has been improved in https://github.com/tuyakhov/yii2-json-api/commit/7dcb7ef9d1f816dbf16671d769318fa5093b4081
