### ISSUE TITLE
Note which versions of PHP we support?

### ISSUE THREAD

**Issue by acorncom** [tuyakhov/yii2-json-api#50]
I support a client on an older version of PHP 5 at the moment (5.4! 😢 ) and the addition of class constants that are arrays broke us when we upgraded to 1.0.6 just now. I'm not asking to support PHP 5.4 for this extension (though the Yii 2.0.x series does support it ...) but could we note somewhere the minimum PHP version that *is* supported?

Per the Scrutinizer config I found, it looks like we're testing against PHP 5.6. Should we be doing multi-environment builds to test against PHP 7.0+ as well?
https://scrutinizer-ci.com/docs/build/multiple_test_environment

**Comment by tuyakhov** [comment]
I have updated the Scrutinizer configuration. So from now on, we test against 2 versions of PHP (5.6.9, 7.1.12). I would like this library to support as much PHP/Yii2 versions as possible. Thank you for pointing this problem out.

**Comment by acorncom** [comment]
Will close this for now, we've just upgraded to PHP 5.6+ for that client
