### ISSUE TITLE
Empty value if is same as filter-attribute

### ISSUE THREAD

**Issue by githubjeka** [tuyakhov/yii2-json-api#7]
<details>

<summary>
Controller
</summary>

```php
class NodeController extends ActiveController
{
    public $serializer = 'tuyakhov\jsonapi\Serializer';

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [           
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/vnd.api+json' => Response::FORMAT_JSON,
                ],
            ],
        ]);
    }

    public function actions()
    {
        return array_merge(
            parent::actions(),
            [
                'index' => [
                    'class' => 'yii\rest\IndexAction',
                    'modelClass' => $this->modelClass,
                    'checkAccess' => [$this, 'checkAccess'],
                    'prepareDataProvider' => function ($action) {
                        $model = new $this->modelClass;
                        return $model->search(\Yii::$app->request->get());
                    }
                ]
            ]
        );
    }

    public $modelClass = 'api\models\Node';
}
```
</details>

<details>

<summary>
Model
</summary>

```php
class Node extends \common\models\Node implements ResourceInterface
{
    public $name; // filter

    use ResourceTrait;

     public function extraFields()
    {
        return ['device',];
    }

    public function fields()
    {
       return ActiveRecord::fields();
    }

    public function search($params)
    {
        $query = self::find()->joinWith(['device', 'device.contract']);

        $dataProvider = new ActiveDataProvider(
            [
                'query' => $query,
            ]
        );
        
        $query ->andFilterWhere(['like', 'node.name', $this->name])
        return $dataProvider;
    }
}
```
</details>

Model has ` public $name; // filter` :

api/nodes

```xml
<response>
<data>
<item>
<id>4025</id>
<type>nodes</type>
<attributes>
<id>4025</id>
<name/> //<-------- empty
```

`var_dump($dataProvider->getModels());die();` returns 

```
array (size=3)
  0 => 
    object(api\models\Node)[225]      
      public 'name' => null
      private '_attributes' (yii\db\BaseActiveRecord) => 
        array (size=63)
          'id' => int 4025          
          'name' => string 'Тестовый узел 2' (length=27)
```

**Comment by tuyakhov** [comment]
Looks like everything is correct. You are "overwriting" the `name` attribute in child class by `public $name;` property which is null in that case. Actually i think it is not a good idea in general to declare public properties in ActiveRecord instance with the same name as one of the attributes you defined.

**Comment by githubjeka** [comment]
I have filters form and have filter named `device` for search by `number` or `name` from relation deviceModel. 

When NodeSearch have `public $device` then I don't see `relationships : {device: {data: {id: "4041", type: "devices"}}}` in response result

**Comment by tuyakhov** [comment]
If i understand correctly the case you have declared public properties which have same name as table columns. More likely you need to rename those properties in `NodeSearch`.
I hope this will help (from [yii2 guide](https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md)):
>Note: The Active Record attributes are named after the associated table columns in a case-sensitive manner. Yii automatically defines an attribute in Active Record for every column of the associated table. You should NOT redeclare any of the attributes.
